### ISSUE TITLE
Namenskonflikt

### ISSUE THREAD

**Issue by josiasmueller** [PATRISPREDICTUM/GenderApp#1]
Hoi! Cooles Projekt zu einem wichtigen Thema.
Meine Frage: Wäre es möglich das Projekt umzubenennen? Es gibt bereits ein gender app, welches im Schweizer Handelsregister eingetragen ist.
Gerne könnt ihr mich kontaktieren: josias.mueller@gmail.com

Liebe Grüsse

**Comment by PATRISPREDICTUM** [comment]
Danke für deine Frage. Lass uns das per E-Mail klären!
